ims_soft/ims_soft/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('profile/', include('users.urls')),
    path('people/', include('people.urls')),
    path('products/', include('products.urls')),
    path('purchases/', include('purchases.urls')),
    path('sales/', include('sales.urls')),
    path('stock/', include('stock.urls')),
    path('reports/', include('reports.urls')),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html',
             extra_context={'header': 'Password Reset'},
         ),
         name='password_reset_complete')
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ims_soft/purchases/urls.py
from django.urls import path

from .views import new_purchase, purchases_list, export_csv, load_purchases, purchase_data, update_purchase, delete_purchase, \
      delete_selected_purchases, auto_complete, ViewPDF

app_name = 'purchases'

urlpatterns = [
    path('new-purchase/', new_purchase, name='new-purchase'),
    path('purchases/', purchases_list, name='purchase-history'),
    path('purchases/data/<int:num>/',
         load_purchases, name='load-data'),
    path('purchases/data/<pk>', purchase_data, name='purchase-data'),
    path('purchases/update/<pk>', update_purchase, name='purchase-update'),
    path('purchases/delete/<pk>', delete_purchase, name='purchase-delete'),
    path('purchases/delete-selected/',
         delete_selected_purchases, name='delete-selected-purchases'),
    # path('sale-report/', sale_report, name='sale-report'),
    path('new-purchase/auto-complete/', auto_complete, name='auto-complete'),
    path('new-purchase/pdf_view', ViewPDF.as_view(), name='pdf-view'),
    path('purchases/export-csv', export_csv, name='export-csv')
]

ims_soft/sales/urls.py
from django.urls import path

from .views import new_sale, sales_list, export_csv, load_sales, sale_data, update_sale, delete_sale, \
      delete_selected_sales, auto_complete, ViewPDF

app_name = 'sales'

urlpatterns = [
    path('new-sale/', new_sale, name='new-sale'),
    path('sales/', sales_list, name='sale-history'),
    path('sales/data/<int:num>/',
         load_sales, name='load-data'),
    path('sales/data/<pk>', sale_data, name='sale-data'),
    path('sales/update/<pk>', update_sale, name='sale-update'),
    path('sales/delete/<pk>', delete_sale, name='sale-delete'),
    path('sales/delete-selected/',
         delete_selected_sales, name='delete-selected-sales'),
    # path('sale-report/', sale_report, name='sale-report'),
    path('new-sale/auto-complete/', auto_complete, name='auto-complete'),
    path('new-sale/pdf_view', ViewPDF.as_view(), name='pdf-view'),
    path('sales/export-csv', export_csv, name='export-csv')
]

ims_soft/sales/models.py
from django.db import models
from django.contrib.auth.models import User

from people.models import Client
from products.models import Product


class Sale(models.Model):
    STATUS_CHOICE = (
        ('pending', 'Pending'),
        ('decline', 'Decline'),
        ('approved', 'Approved'),
        ('processing', 'Processing'),
        ('complete', 'Complete'),
        ('bulk', 'Bulk'),
    )
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product)
    sub_total = models.PositiveIntegerField(blank=True, null=True, default=0)
    discount = models.PositiveIntegerField(blank=True, null=True, default=0)
    tax = models.PositiveIntegerField(blank=True, null=True, default=0)
    grand_total = models.PositiveIntegerField(null=True, default=0)
    payment = models.PositiveIntegerField(blank=True, null=True, default=0)
    left_to_pay = models.PositiveIntegerField(blank=True, null=True, default=0)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICE, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.RESTRICT ,blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)

    class Meta:
        ordering = ('-id', )

    def __str__(self):
        return f"sale N°: {self.id}"

ims_soft/sales/forms.py
from django import forms
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Field, Submit
from django.forms import models
from django.forms import formset_factory

from .models import Sale
from products .models import Product
from people.models import Client


class SaleForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field('payment', id="id_updatePayment"),
        )
        self.helper.add_input(
            Submit('submit', 'Submit', css_class='btn-primary'))
        self.helper.form_method = 'POST'
        super(SaleForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Sale
        exclude = ('client', 'products', 'discount', 'tax', 'discount',
                   'status', 'left_to_pay', 'created_by', 'created_at')


class CreateClientForm(forms.ModelForm):
    # created_at = forms.DateInput()
    client = forms.ModelChoiceField(queryset=Client.objects.all(), widget=forms.Select(attrs={'class':'custom-select'}))  
    sub_total = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control', 'readonly':'readonly'}), initial=0)
    discount = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}), initial=0)
    tax = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}), initial=0)
    grand_total = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control', 'readonly':'readonly'}), initial=0)
    payment = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}), initial=0)
    left_to_pay = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control', 'readonly':'readonly'}), initial=0)
    class Meta:
        model = Client
        fields = ['client', 'sub_total', 'discount', 'tax','grand_total', 'payment', 'left_to_pay']



class ProductSaleForm(forms.Form):
    products = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control'}))
    sale_price = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'readonly':'readonly'}), initial=0)
    quantity = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control'}))
    total_amount = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'readonly':'readonly'}), initial=0)
ProductFormSet = formset_factory(ProductSaleForm, extra=1)

ims_soft/sales/views.py
from django.forms import models
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from django.views import View
from xhtml2pdf import context
from django.urls import reverse_lazy

from .models import Sale
from .forms import SaleForm, CreateClientForm, ProductFormSet
from .resources import SaleResource
from products.models import Product
from purchases.models import ProductAttribute
from stock.models import Barcode
from .utils import render_to_pdf, get_status


def new_sale(request):
    sales = Sale.objects.all()
    form = CreateClientForm(request.POST or None)
    formset = ProductFormSet(request.POST or None)
    if request.method == 'POST':
        formset = ProductFormSet(request.POST)
        if form.is_valid() & formset.is_valid():
            instance = form.save(commit=False)
            instance.created_by = request.user
            instance.save()
            products = formset.cleaned_data
            for product in products:
                qs = Product.objects.get(name=product['products'])
                prodattr = ProductAttribute.objects.filter(pk=qs.id)
                if prodattr:
                    prodattr.update(quantity=prodattr.first().quantity - int(product['quantity'])) 
            return redirect(reverse_lazy("sales:pdf-view"))
    context = {
        'sales': sales,
        'section_title': 'Sales',
        'title': 'New-Sale',
        'formset': formset,
        'form': form
    }
    return render(request, 'sales/new_sale.html', context)


# class PurchaseAddView(TemplateView):
#     template_name = "purchases/new_purchase.html"

#     # Define method to handle GET request
#     def get(self, *args, **kwargs):
#         # Create an instance of the formset
#         formset = PurchaseFormSet(queryset=Purchase.objects.none())
#         return self.render_to_response({'purchase_formset': formset})
    
#     # Define method to handle POST request
#     def post(self, request, *args, **kwargs):
#         user = request.user
#         formset = PurchaseFormSet(data=self.request.POST)

#         # Check if submitted forms are valid
#         if formset.is_valid():
#             instance = formset.save(commit=False)
#             instance.created_by = user
#             print(instance)     
#             formset.save()
#             return redirect(reverse_lazy("purchases:purchase-history"))

#         return self.render_to_response({'purchase_formset': formset})


def sales_list(request):
    form = SaleForm(request.POST or None)
    context = {
        'section_title': 'Sales',
        'title': 'Sale History',
        'form': form
    }
    return render(request, 'sales/sale_history.html', context)


@login_required
def load_sales(request, num):
    if request.is_ajax():
        visible = 5
        upper = num
        lower = upper - visible
        size = Sale.objects.all().count()
        qs = Sale.objects.all()
        data = []
        for obj in qs:
            get_status(obj)
            item = {
                'id': obj.id,
                'client': obj.client.name,
                'created_at': obj.created_at,
                'status': obj.status,
                'grand_total': obj.grand_total,
                'payment': obj.payment,
                'created_by': obj.created_by.username,
            }
            data.append(item)

        return JsonResponse({'data': data[lower:upper], 'size': size})


@login_required
def update_sale(request, pk):
    if request.is_ajax():
        obj = Sale.objects.get(pk=pk)
        new_payment = request.POST.get('payment')
        obj.payment = new_payment
        get_status(obj)
        obj.save()  
        return JsonResponse({
            'payment': obj.payment,
            'status': obj.status
        })
    return redirect('sales:sale-history')


@login_required
def sale_data(request, pk):
    if request.is_ajax():
        obj = Sale.objects.get(pk=pk)
        data = {
            'id': obj.id,
            'client': obj.client.name,
            'created_at': obj.created_at,
            'status': obj.status,
            'grand_total': obj.grand_total,
            'payment': obj.payment,
            'created_by': obj.created_by.username,
        }
        return JsonResponse({'data': data})

    return redirect('sales:sale-history')


@login_required
def delete_sale(request, pk):
    if request.is_ajax():
        obj = Sale.objects.get(pk=pk)
        obj.delete()
        return JsonResponse({'msg': 'Object has been deleted'})
    return redirect('sales:sale-history')


def delete_selected_sales(request):
    if request.is_ajax():
        object_ids = request.POST.getlist(('id_list[]'))
        for id in object_ids:
            obj = Sale.objects.get(pk=id)
            obj.delete()
        return JsonResponse({'msg': 'Objects have been deleted'})
    return redirect('sales:sale-history')

# data = {
# 	"company": "Dennnis Ivanov Company",
# 	"address": "123 Street name",
# 	"city": "Vancouver",
# 	"state": "WA",
# 	"zipcode": "98663",


# 	"phone": "555-555-2345",
# 	"email": "youremail@dennisivy.com",
# 	"website": "dennisivy.com",
# 	}

# Opens up page as PDF
# qs = Barcode.objects.all()
# data = {}
# for obj in qs:

#     item = {
#         'id': obj.id,
#         'barcode_digit': obj.barcode_digit,
#         'barcode_img': obj.barcode_img
#     }
#     data.update(item)


class ViewPDF(View):

    def get(self, request, *args, **kwargs):
        pdf = render_to_pdf('sales/pdf_template.html', data)
        return HttpResponse(pdf, content_type='application/pdf')


def auto_complete(request):
    if request.is_ajax():
        qs = Product.objects.all()
        data = []
        for obj in qs:
            item = {
                'name': obj.name,
            }
            data.append(item)
        return JsonResponse({'data': data})
    return redirect('sales:sale-history')

def export_csv(request):
    product_resource = SaleResource()
    dataset = product_resource.export()
    response = HttpResponse(dataset.csv, content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="sale_history.csv"'
    return response

ims_soft/sales/templates/sales/new_sale.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}
<script src="{% static 'sales/new.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
    New Sale
{% endblock title %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <!-- [ New Sale Content ] start -->
        <div class="d-flex flex-wrap justify-content-center">
            <!-- [ sample-page ] start -->
            <div class="col-sm-8">
                <div class="card">
                    <div class="card-header">
                        <h5>New Sale</h5>
                        <div class="card-header-right">
                            <div class="btn-group card-option">
                                <button type="button" class="btn dropdown-toggle btn-icon" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="feather icon-more-horizontal"></i>
                                </button>
                                <ul class="list-unstyled card-option dropdown-menu dropdown-menu-right">
                                    <li class="dropdown-item full-card"><a href="#!"><span><i class="feather icon-maximize"></i> maximize</span><span style="display:none"><i class="feather icon-minimize"></i> Restore</span></a></li>
                                    <li class="dropdown-item minimize-card"><a href="#!"><span><i class="feather icon-minus"></i> collapse</span><span style="display:none"><i class="feather icon-plus"></i> expand</span></a></li>
                                    <li class="dropdown-item reload-card"><a href="#!"><i class="feather icon-refresh-cw"></i> reload</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="card-body justify-content-between">
                        <div class="d-flex flex-wrap justify-content-around">
                            <div class="form-group col-md-6">
                                <label for="inputName" class="d-flex flex-wrap justify-content-center">Client Name</label>
                                <div class="input-group mb-3">
                                    {{ form.client }}
                                </div>
                            </div>
                            <!-- <div class="form-group col-md-6">
                                <label for="inputLname" class="d-flex flex-wrap justify-content-center">Sale
                                    Date</label>
                                <div class="d-flex flex-wrap justify-content-center">
                                    <input type="text" id="datepicker" class="text-center" width="412"
                                        style="padding-bottom: 1.2rem;" required />
                                </div>
                            </div> -->
                        </div>
                    </div>
                </div>
            </div>
            <!-- [ sample-page ] end -->
        </div>
        <div class="d-flex flex-wrap justify-content-center">
            <!-- [ sample-page ] start -->
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>New Sale</h5>
                        <div class="card-header-right">
                            <div class="btn-group card-option">
                                <button type="button" class="btn dropdown-toggle btn-icon" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="feather icon-more-horizontal"></i>
                                </button>
                                <ul class="list-unstyled card-option dropdown-menu dropdown-menu-right">
                                    <li class="dropdown-item full-card"><a href="#!"><span><i class="feather icon-maximize"></i> maximize</span><span style="display:none"><i class="feather icon-minimize"></i> Restore</span></a></li>
                                    <li class="dropdown-item minimize-card"><a href="#!"><span><i class="feather icon-minus"></i> collapse</span><span style="display:none"><i class="feather icon-plus"></i> expand</span></a></li>
                                    <li class="dropdown-item reload-card"><a href="#!"><i class="feather icon-refresh-cw"></i> reload</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="card-body table-border-style">
                            <div class="d-flex flex-wrap justify-content-between">
                                <div class="col-sm-1">
                                    <button id="add-form" type="button" class="btn btn-icon btn-success mt-3" data-toggle="tooltip" data-placement="top" title="Add item">
                                        <i class="feather icon-plus"></i>
                                    </button>
                                </div> 
                                <div class="col-sm-11 table-responsive">
                                    <table id="form-container" class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>Product</th>
                                                <th>Unit Price</th>
                                                <th>Quantity</th>
                                                <th>Total Amount</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {{formset.management_form}}
                                            {% for formpro in formset %}
                                                <tr class="purchase-form">
                                                    <td>{{formpro.products}}</td>
                                                    <td>{{formpro.sale_price}}</td>
                                                    <td>{{formpro.quantity}}</td>
                                                    <td>{{formpro.total_amount}}</td>
                                                </tr>
                                            {% endfor %}
                                            <tr>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td class="new_sale-td">Sub Totla</td>
                                                <td class="new_sale-td">
                                                    {{ form.sub_total }}
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td class="new_sale-td">Discount</td>
                                                <td class="new_sale-td">
                                                    {{ form.discount }}
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td class="new_sale-td">Tax</td>
                                                <td class="new_sale-td">
                                                    {{ form.tax }}
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td class="new_sale-td">Grand Total</td>
                                                <td class="new_sale-td">
                                                    {{ form.grand_total }}
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td class="new_sale-td">Payment</td>
                                                <td class="new_sale-td">
                                                    {{ form.payment }}
                                                </td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td class="new_sale-td">Left To Pay</td>
                                                <td class="new_sale-td">{{ form.left_to_pay }}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <div id="spinner-box" class="text-center not-visible">
                                        <div class="spinner-border mb-3" role="status"></div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-10">
                                            <button type="submit" class="btn  btn-primary">Create Sale</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- [ sample-page ] end -->
        </div>
    <!-- [ New Sale Content ] end -->
</form>
{% endblock content %}

ims_soft/sales/templates/sales/sale_history.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block scripts %}
<script src="{% static 'sales/main.js' %}" defer></script>
<script src="{% static 'sales/actions.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
Sales
{% endblock title %}


{% block content %}
<!-- [ Sale History Content ] start -->

<!-- Update Modal -->
<div id="updateModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel1">Update Payment</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <form id="update-form" autocomplete="off">
                    {% csrf_token %}
                    {% crispy form %}
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Delete  start -->
<div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel3"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel3">Delete Sale</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <p class="mb-2">Are you sure you want to delete: </p>
                <p id="delMsgName"></p>
            </div>
            <div class="modal-footer">
                <form id="delete-form">
                    {% csrf_token %}
                    <button type="button" class="btn  btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn  btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Delete Selected start -->
<div id="deleteSelectedModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel4"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel4">Delete Selected Purchases</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <p id="delSelMsg" class="mb-0"></p>
            </div>
            <div class="modal-footer">
                <form id="delete-selected-form">
                    {% csrf_token %}
                    <button type="button" class="btn  btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn  btn-danger" id="submitDelSel">Ok</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <!-- [ sample-page ] start -->
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                <h5>Sale History</h5>
                <div class="d-flex flex-wrap justify-content-around mt-3">
                    <div>
                        <button type="button" class="btn btn-danger" id="delete-selected-btn" data-toggle="modal"
                            data-target="#deleteSelectedModal">Delete Selection
                        </button>
                    </div>
                    <div>
                        <a href="{% url 'purchases:export-csv' %}" class="btn btn-info mr-3">Export .Csv</a>
                    </div>
                </div>
                <div class="card-header-right">
                    <div class="btn-group card-option">
                        <button type="button" class="btn dropdown-toggle btn-icon" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <i class="feather icon-more-horizontal"></i>
                        </button>
                        <ul class="list-unstyled card-option dropdown-menu dropdown-menu-right">
                            <li class="dropdown-item full-card"><a href="#!"><span><i class="feather icon-maximize"></i>
                                        maximize</span><span style="display:none"><i class="feather icon-minimize"></i>
                                        Restore</span></a></li>
                            <li class="dropdown-item minimize-card"><a href="#!"><span><i
                                            class="feather icon-minus"></i> collapse</span><span style="display:none"><i
                                            class="feather icon-plus"></i> expand</span></a>
                            </li>
                            <li class="dropdown-item reload-card"><a href="#!"><i class="feather icon-refresh-cw"></i>
                                    reload</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="card-body table-border-style">
                <div class="d-flex flex-wrap justify-content-center mb-3">
                    <div class="col-sm-6">
                        <input id="search-input" type="text" class="form-control" placeholder="Search here...">
                    </div>
                </div>
                <div id="alert-box"></div>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>N°</th>
                                <th>Client</th>
                                <th>Sale Date</th>
                                <th>Status</th>
                                <th>Grand Total</th>
                                <th>Payment</th>
                                <th>Saled By</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody id="rows-box"></tbody>
                    </table>
                    <div id="spinner-box" class="text-center">
                        <div class="spinner-border mb-3" role="status"></div>
                    </div>
                    <div class="text-center mb-3" id="end-box">
                        <button class="btn btn-primary" id="load-btn">Load more</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- [ sample-page ] end -->
</div>
<!-- [ Sale History Content ] end -->
{% endblock content %}