ims_soft/ims_soft/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('profile/', include('users.urls')),
    path('people/', include('people.urls')),
    path('products/', include('products.urls')),
    path('purchases/', include('purchases.urls')),
    path('sales/', include('sales.urls')),
    path('stock/', include('stock.urls')),
    path('reports/', include('reports.urls')),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html',
             extra_context={'header': 'Password Reset'},
         ),
         name='password_reset_complete')
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ims_soft/sales/urls.py
from django.urls import path

from .views import new_sale, sales_list, export_csv, load_sales, sale_data, update_sale, delete_sale, \
      delete_selected_sales, auto_complete, ViewPDF

app_name = 'sales'

urlpatterns = [
    path('new-sale/', new_sale, name='new-sale'),
    path('sales/', sales_list, name='sale-history'),
    path('sales/data/<int:num>/',
         load_sales, name='load-data'),
    path('sales/data/<pk>', sale_data, name='sale-data'),
    path('sales/update/<pk>', update_sale, name='sale-update'),
    path('sales/delete/<pk>', delete_sale, name='sale-delete'),
    path('sales/delete-selected/',
         delete_selected_sales, name='delete-selected-sales'),
    # path('sale-report/', sale_report, name='sale-report'),
    path('new-sale/auto-complete/', auto_complete, name='auto-complete'),
    path('new-sale/pdf_view', ViewPDF.as_view(), name='pdf-view'),
    path('sales/export-csv', export_csv, name='export-csv')
]

ims_soft/stock/urls.py
from django import views
from django.urls import path

from .views import stock_list, load_stock, update_stock, stock_data, ViewPDF, export_csv

app_name = 'stock'

urlpatterns = [
    path('stock-list/', stock_list, name='stock-list'),
    path('stock-list/data/<int:num>/',
         load_stock, name='stock-data'),
    path('stock-list/data/<pk>', stock_data, name='stock-data'),
    path('stock-list/update/<pk>', update_stock, name='stock-update'),
    path('stock-list/pdf_view', ViewPDF.as_view(), name='pdf-view'),
    path('stock-list/export-csv', export_csv, name='export-csv'),
]

ims_soft/stock/models.py
from purchases.models import ProductAttribute
from django.db import models
from django.core.files import File
import barcode
from barcode.writer import ImageWriter
from io import BytesIO
import string
import secrets

from users.models import Company

# class ProductStock(models.Model):
#     STATUS_CHOICE = (
#         ('unavailable', 'unavailable'),
#         ('low', 'low'),
#         ('medium', 'medium'),
#         ('available', 'available')
#     )
#     product = models.OneToOneField(Product, on_delete=models.CASCADE)
#     product_attribute = models.ForeignKey(ProductAttribute, on_delete=models.RESTRICT, blank=True, null=True)
#     buy_price = models.PositiveIntegerField(blank=True, null=True)
#     sale_price = models.PositiveIntegerField(blank=True, null=True)
#     discount = models.PositiveIntegerField(blank=True, null=True)
#     reorder_level = models.IntegerField(default=0, blank=True, null=True)
#     status = models.CharField(max_length=11, choices=STATUS_CHOICE, blank=True, null=True)

#     class Meta:
#         ordering = ('-id', )
#         verbose_name = 'Stock'
#         verbose_name_plural = 'Stock'
    
#     def save(self, *args, **kwargs):
#         qs = Purchase.objects.get(id=self.purchase.id)
#         self.quantity += qs.qhantity
#         return super().save(*args, **kwargs)

#     def __str__(self):
#         return self.product.name


class Barcode(models.Model):
    product = models.OneToOneField(ProductAttribute, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.RESTRICT, blank=True, null=True, default=1)
    barcode_digit = models.CharField(max_length=13, blank=True, null=True)
    barcode_img = models.ImageField(upload_to='images/barcodes/', blank=True)
    # country_id = models.CharField(max_length=1, null=True)
    # manufacturer_id = models.CharField(max_length=6, null=True)
    # number_id = models.CharField(max_length=5, null=True)

    def save(self, *args, **kwargs):
        if not self.barcode_digit:
            alphabet = string.ascii_letters + string.digits
            code = f'{self.company.name[:3]}' + ''.join(secrets.choice(alphabet) for i in range(9))
            code_39 = barcode.get_barcode_class('code39')
            code39_digit = code_39(code)
            self.barcode_digit = code39_digit
            code39_image = code_39(code, writer=ImageWriter())
            buffer = BytesIO()
            code39_image.write(buffer)
            self.barcode_img.save(f'{self.product.product.name}_code.png', File(buffer), save=False)
            return super().save(*args, **kwargs)
    
    class Meta:
        ordering = ('-id', )
    
    def __str__(self):
        return f"Barcode of: {self.product.product.name}"

ims_soft/stock/forms.py
from purchases.models import ProductAttribute
from django import forms
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Field, Submit



class StockForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field('reorder_level', id="id_updateReorderLevel"),
        )
        self.helper.add_input(
            Submit('submit', 'Submit', css_class='btn-primary'))
        self.helper.form_method = 'POST'
        super(StockForm, self).__init__(*args, **kwargs)

    class Meta:
        model = ProductAttribute
        exclude = ('product', 'quantity', 'buy_price',
                   'sale_price', 'discount', 'status')

ims_soft/stock/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from django.views import View
from xhtml2pdf import context

from .models import Barcode
from .forms import StockForm
from .utils import get_status, get_barcode, render_to_pdf
from .resources import ProductStockResource
from purchases.models import ProductAttribute


def stock_list(request):
    form = StockForm(request.POST or None)
    context = {
        'section_title': 'Stock',
        'title': 'List-Stock',
        'form': form
    }
    return render(request, 'stock/list_stock.html', context)


@login_required
def load_stock(request, num):
    if request.is_ajax():
        visible = 5
        upper = num
        lower = upper - visible
        size = ProductAttribute.objects.all().count()
        qs = ProductAttribute.objects.all()
        data = []
        for obj in qs:
            get_status(obj)
            barcode = Barcode.objects.get(product=obj.id)
            item = {
                'id': obj.id,
                'product': obj.product.name,
                'quantity': obj.quantity,
                'buy_price': obj.buy_price,
                'sale_price': obj.sale_price,
                'reorder_level': obj.reorder_level,
                'status': obj.status,
                'barcode_digit': barcode.barcode_digit
            }
            data.append(item)

        return JsonResponse({'data': data[lower:upper], 'size': size})


@login_required
def update_stock(request, pk):
    if request.is_ajax():
        obj = ProductAttribute.objects.get(pk=pk)
        print(obj)
        new_reorder_level = request.POST.get('reorder_level')
        obj.reorder_level = new_reorder_level
        get_status(obj)
        obj.save()
        return JsonResponse({
            'status': obj.status
        })

    return redirect('stock:stock-list')


@login_required
def stock_data(request, pk):
    if request.is_ajax():
        obj = ProductAttribute.objects.get(pk=pk)
        barcode = Barcode.objects.get(product=obj.id)
        data = {
            'id': obj.id,
            'reorder_level': obj.reorder_level,
            'status': obj.status,
            'barcode_img': barcode.barcode_img.url
        }
        return JsonResponse({'data': data})

    return redirect('stock:stock-list')


data = {
	"company": "Dennnis Ivanov Company",
	"address": "123 Street name",
	"city": "Vancouver",
	"state": "WA",
	"zipcode": "98663",


	"phone": "555-555-2345",
	"email": "youremail@dennisivy.com",
	"website": "dennisivy.com",
	}


class ViewPDF(View):
    data = get_barcode
    def get(self, request, *args, **kwargs):
        pdf = render_to_pdf('stock/pdf_template.html', data)
        return HttpResponse(pdf, content_type='application/pdf')


def export_csv(request):
    product_resource = ProductStockResource()
    dataset = product_resource.export()
    response = HttpResponse(dataset.csv, content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="products_stock.csv"'
    return response

ims_soft/stock/templates/stock/fr/list_categories.html
{% extends 'base.html' %}
{% load static %}


{% block scripts %}
    <script src="{% static 'products/main.js' %}" defer></script>
    <script src="{% static 'products/actions.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
    Categories List
{% endblock title %}


{% block content %}
<!-- [ List Products Content ] start -->

<!-- Create Category Modal -->
<div id="addModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel">Create Category</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div id="alertModal-box"></div>
                <form id="create-form" autocomplete="off">
              
                    <div class="">
                        <button type="button" class="btn  btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" id="add-btn" class="btn  btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Update  Modal -->
<div id="updateModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel2">Update Category</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <form id="update-form" autocomplete="off">
                   
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Delete  start -->
<div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel3"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel3">Delete Product</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <p id="delMsg" class="mb-0">Are you sure you want to delete: </p>
            </div>
            <div class="modal-footer">
                <form id="delete-form">
                    {% csrf_token %}
                    <button type="button" class="btn  btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn  btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row justify-content-center">
    <!-- [ sample-page ] start -->
    <div class="col-sm-9">
        <div class="card">
            <div class="card-header">
                <h5>Categories</h5>
                <button type="button" class="btn  btn-success" data-toggle="modal" data-target="#addModal"> add +
                </button>
                <div class="card-header-right">
                    <div class="btn-group card-option">
                        <button type="button" class="btn dropdown-toggle btn-icon" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <i class="feather icon-more-horizontal"></i>
                        </button>
                        <ul class="list-unstyled card-option dropdown-menu dropdown-menu-right">
                            <li class="dropdown-item full-card"><a href="#!"><span><i class="feather icon-maximize"></i>
                                        maximize</span><span style="display:none"><i class="feather icon-minimize"></i>
                                        Restore</span></a></li>
                            <li class="dropdown-item minimize-card"><a href="#!"><span><i
                                            class="feather icon-minus"></i> collapse</span><span style="display:none"><i
                                            class="feather icon-plus"></i> expand</span></a>
                            </li>
                            <li class="dropdown-item reload-card"><a href="#!"><i class="feather icon-refresh-cw"></i>
                                    reload</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="card-body table-border-style">
                <div class="d-flex flex-wrap justify-content-center mb-3">
                    <div class="col-sm-6">
                        <input id="search-input" type="text" class="form-control" placeholder="Search here...">
                    </div>
                </div>
                <div id="alert-box"></div>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Category</th>
                                <th>Products</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody id="rows-box"></tbody>
                    </table>
                    <div id="spinner-box" class="text-center">
                        <div class="spinner-border mb-3" role="status"></div>
                    </div>
                    <div class="text-center mb-3" id="end-box">
                        <button class="btn btn-primary" id="load-btn">Load more</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ sample-page ] end -->
    </div>
    <!-- [ sample-page ] end -->
</div>
<!-- [ List Products Content ] start -->
{% endblock content %}

ims_soft/stock/templates/stock/fr/list_products.html
{% extends 'base.html' %}
{% load static %}


{% block scripts %}
    <script src="{% static 'products/main.js' %}" defer></script>
    <script src="{% static 'products/actions.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
    Products List
{% endblock title %}


{% block content %}
<!-- [ List Products Content ] start -->

<!-- Create Product Modal -->
<div id="addModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel">Create Product</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div id="alertModal-box"></div>
                <form id="create-form" autocomplete="off">
              
                    <div class="">
                        <button type="button" class="btn  btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" id="add-btn" class="btn  btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Update  Modal -->
<div id="updateModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel2">Update Product</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <form id="update-form" autocomplete="off">
                   
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Delete  start -->
<div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel3"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel3">Delete Product</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <p id="delMsg" class="mb-0">Are you sure you want to delete: </p>
            </div>
            <div class="modal-footer">
                <form id="delete-form">
                    {% csrf_token %}
                    <button type="button" class="btn  btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn  btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <!-- [ sample-page ] start -->
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                <h5>Products</h5>
                <button type="button" class="btn  btn-success" data-toggle="modal" data-target="#addModal"> add +
                </button>
                <div class="card-header-right">
                    <div class="btn-group card-option">
                        <button type="button" class="btn dropdown-toggle btn-icon" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <i class="feather icon-more-horizontal"></i>
                        </button>
                        <ul class="list-unstyled card-option dropdown-menu dropdown-menu-right">
                            <li class="dropdown-item full-card"><a href="#!"><span><i class="feather icon-maximize"></i>
                                        maximize</span><span style="display:none"><i class="feather icon-minimize"></i>
                                        Restore</span></a></li>
                            <li class="dropdown-item minimize-card"><a href="#!"><span><i
                                            class="feather icon-minus"></i> collapse</span><span style="display:none"><i
                                            class="feather icon-plus"></i> expand</span></a>
                            </li>
                            <li class="dropdown-item reload-card"><a href="#!"><i class="feather icon-refresh-cw"></i>
                                    reload</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="card-body table-border-style">
                <div class="d-flex flex-wrap justify-content-center mb-3">
                    <div class="col-sm-6">
                        <input id="search-input" type="text" class="form-control" placeholder="Search here...">
                    </div>
                </div>
                <div id="alert-box"></div>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Product Name</th>
                                <th>Article N°</th>
                                <th>Category</th>
                                <th>In Stock</th>
                                <th>Barcode</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody id="rows-box"></tbody>
                    </table>

                    

                    <div id="spinner-box" class="text-center">
                        <div class="spinner-border mb-3" role="status"></div>
                    </div>
                    <div class="text-center mb-3" id="end-box">
                        <button class="btn btn-primary" id="load-btn">Load more</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ sample-page ] end -->
    </div>
    <!-- [ sample-page ] end -->
</div>
<!-- [ List Products Content ] start -->
{% endblock content %}

ims_soft/stock/templates/stock/fr/list_stock_fr.html
{% load static %}

{% block content %}
<!-- [ List Products Content ] start -->
<!-- Update Modal -->
<div id="updateModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel2">Update Reorder Level</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <form id="update-form" autocomplete="off">
                    {% csrf_token %}
                    {% crispy form %}
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Update Modal -->
<div id="updateModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel2">Update Reorder Level</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div id="spinner-modal" class="text-center">
                    <div class="spinner-border mb-3" role="status"></div>
                </div>
                <form id="print-form" class="printform">
            </div>
        </div>
    </div>
</div>

<!-- Print Modal -->
<div id="printModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel2">Imprimer code à barre </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div id="spinner-modal" class="text-center">
                    <div class="spinner-border mb-3" role="status"></div>
                </div>
                <form id="print-form" class="printform">
            </div>
        </div>
    </div>
</div>

<div class="row">
    <!-- [ sample-page ] start -->
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                <h5>Stock</h5>
                <div class="d-flex flex-wrap justify-content-around mt-3">

                    <div>
                        <a href="{% url 'stock:export-csv' %}" class="btn btn-info">Exporter .Csv</a>
                    </div>
                </div>
                <div class="card-header-right">
                    <div class="btn-group card-option">
                        <button type="button" class="btn dropdown-toggle btn-icon" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <i class="feather icon-more-horizontal"></i>
                        </button>
                        <ul class="list-unstyled card-option dropdown-menu dropdown-menu-right">
                            <li class="dropdown-item full-card"><a href="#!"><span><i class="feather icon-maximize"></i>
                                        maximiser</span><span style="display:none"><i class="feather icon-minimize"></i>
                                        restaurer</span></a></li>
                            <li class="dropdown-item minimize-card"><a href="#!"><span><i
                                            class="feather icon-minus"></i> s'effondrer</span><span
                                        style="display:none"><i class="feather icon-plus"></i> agrandir</span></a>
                            </li>
                            <li class="dropdown-item reload-card"><a href="#!"><i class="feather icon-refresh-cw"></i>
                                    recharger</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="card-body table-border-style">
                <div id="alert-box"></div>
                <div class="dt-responsive table-responsive">
                    <table id="row-delete" class="table table-striped table-bordered nowrap ">
                        <thead>
                            <tr>
                                <th>Nom du produit</th>
                                <th>N° d'Article</th>
                                <th>Categorie</th>
                                <th>Quantité</th>
                                <th>Prix d'achat</th>
                                <th>Prix de vente</th>
                                <th>Code à barre</th>
                            </tr>
                        </thead>
                        <tbody id="rows-box"></tbody>
                    </table>
                    <div id="spinner-box" class="text-center">
                        <div class="spinner-border mb-3" role="status"></div>
                    </div>
                    <div class="text-center mb-3 mt-3" id="end-box">
                        <button class="btn btn-primary" id="load-btn">Charger plus</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ sample-page ] end -->
    </div>
    <!-- [ sample-page ] end -->
</div>
<!-- [ List Products Content ] start -->
{% endblock content %}