ims_soft/ims_soft/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('profile/', include('users.urls')),
    path('people/', include('people.urls')),
    path('products/', include('products.urls')),
    path('purchases/', include('purchases.urls')),
    path('sales/', include('sales.urls')),
    path('stock/', include('stock.urls')),
    path('reports/', include('reports.urls')),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html',
             extra_context={'header': 'Password Reset'},
         ),
         name='password_reset_complete')
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ims_soft/products/urls.py
from django.urls import path

from .views import (categories_list_and_create, load_categories, category_data, update_category, delete_category, delete_selected_categories,
                    products_list_and_create, load_products, product_data, update_product, delete_product, delete_selected_products, export_csv)

app_name = 'products'

urlpatterns = [
    path('categories/', categories_list_and_create, name='categories'),
    path('categories/data/<int:num>/',
         load_categories, name='categories-data'),
    path('categories/update/<pk>', update_category, name='suppplier-update'),
    path('categories/data/<pk>', category_data, name='category-data'),
    path('categories/delete/<pk>', delete_category, name='category-delete'),
    path('categories/delete-selected/',
         delete_selected_categories, name='delete-selected-categories'),

    path('products/', products_list_and_create, name='products'),
    path('products/data/<int:num>/',
         load_products, name='products-data'),
    path('products/update/<pk>', update_product, name='product-update'),
    path('products/data/<pk>', product_data, name='product-data'),
    path('products/delete/<pk>', delete_product, name='product-delete'),
    path('products/delete-selected/',
         delete_selected_products, name='delete-selected-products'),
    path('products/export-csv', export_csv, name='export-csv'),

]

ims_soft/sales/urls.py
from django.urls import path

from .views import new_sale, sales_list, export_csv, load_sales, sale_data, update_sale, delete_sale, \
      delete_selected_sales, auto_complete, ViewPDF

app_name = 'sales'

urlpatterns = [
    path('new-sale/', new_sale, name='new-sale'),
    path('sales/', sales_list, name='sale-history'),
    path('sales/data/<int:num>/',
         load_sales, name='load-data'),
    path('sales/data/<pk>', sale_data, name='sale-data'),
    path('sales/update/<pk>', update_sale, name='sale-update'),
    path('sales/delete/<pk>', delete_sale, name='sale-delete'),
    path('sales/delete-selected/',
         delete_selected_sales, name='delete-selected-sales'),
    # path('sale-report/', sale_report, name='sale-report'),
    path('new-sale/auto-complete/', auto_complete, name='auto-complete'),
    path('new-sale/pdf_view', ViewPDF.as_view(), name='pdf-view'),
    path('sales/export-csv', export_csv, name='export-csv')
]

ims_soft/products/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=50, db_index=True, unique=True, default='undefined')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('created_at', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class Product(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    article_num = models.CharField(max_length=6)
    created_by = models.ForeignKey(User, on_delete=models.RESTRICT)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('created_at', )

ims_soft/products/forms.py
from django import forms
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Field, Submit

from .models import Category, Product


class CategoryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field('name', id="id_updateName"),
        )
        self.helper.add_input(Submit('submit', 'Submit', css_class='btn-primary'))
        self.helper.form_method = 'POST'
        super(CategoryForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Category
        exclude = ('created_at',)


class ProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field('name', id="id_updateName"),
            Field('category', id="id_updateCategory"),
            Field('article_num', id="id_updateArticle_num"),
        )
        self.helper.add_input(Submit('submit', 'Submit', css_class='btn-primary'))
        self.helper.form_method = 'POST'
        super(ProductForm, self).__init__(*args, **kwargs)
       
    class Meta:
        model = Product
        exclude = ('created_by', 'created_at', 'updated_at')

ims_soft/products/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from .utils import load_objects, objects_list_and_create, object_data, update_object, delete_object, \
    delete_selected_objects
from .forms import ProductForm, CategoryForm
from .resources import ProductResource


@login_required
def categories_list_and_create(request):
    form = CategoryForm(request.POST or None)
    if request.is_ajax():
        return objects_list_and_create(request, form)
    context = {
        'section_title': 'Categories',
        'title': 'List-Categories',
        'form': form
    }
    return render(request, 'products/list_categories.html', context)


@login_required
def load_categories(request, num):
    if request.is_ajax():
        return load_objects(request, num, "Category")
    return redirect('products:categories')


@login_required
def category_data(request, pk):
    if request.is_ajax():
        return object_data(request, "Category", pk)
    return redirect('products:categories')


@login_required
def update_category(request, pk):
    if request.is_ajax():
        return update_object(request, "Category", pk)
    return redirect('products:categories')


@login_required
def delete_category(request, pk):
    if request.is_ajax():
        return delete_object(request, "Category", pk)
    return redirect('products:categories')


def delete_selected_categories(request):
    if request.is_ajax():
        return delete_selected_objects(request, "Category")
    return redirect('products:categories')


def products_list_and_create(request):
    form = ProductForm(request.POST or None)
    if request.is_ajax():
        return objects_list_and_create(request, form)
    context = {
        'section_title': 'Products',
        'title': 'List-Products',
        'form': form
    }
    return render(request, 'products/list_products.html', context)


@login_required
def load_products(request, num):
    if request.is_ajax():
        return load_objects(request, num, "Product")
    return redirect('products:products')


@login_required
def product_data(request, pk):
    if request.is_ajax():
        return object_data(request, "Product", pk)
    return redirect('products:products')


@login_required
def update_product(request, pk):
    if request.is_ajax():
        return update_object(request, "Product", pk)
    return redirect('products:products')


@login_required
def delete_product(request, pk):
    if request.is_ajax():
        return delete_object(request, "Product", pk)
    return redirect('products:products')


def delete_selected_products(request):
    if request.is_ajax():
        return delete_selected_objects(request, "Product")
    return redirect('products:products')


def export_csv(request):
    product_resource = ProductResource()
    dataset = product_resource.export()
    response = HttpResponse(dataset.csv, content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="products.csv"'
    return response

ims_soft/products/templates/products/fr/list_categories_fr.html
{% load static %}

{% block content %}
<!-- [ List Categories Content ] start -->

<!-- Create Category Modal -->
<div id="addModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel">Créer une categorie</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div id="alertModal-box"></div>
                <form id="create-form" autocomplete="off">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="">
                        <button type="button" class="btn  btn-secondary" data-dismiss="modal">Fermer</button>
                        <button type="submit" id="add-btn" class="btn  btn-primary">Sauvegarder</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Update  Modal -->
<div id="updateModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel2">Mettre à jour la categorie</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <form id="update-form" autocomplete="off">
                    {% csrf_token %}
                    {% crispy form %}
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Delete start -->
<div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel3"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel3">Supprimer la categorie</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <p id="delMsg" class="mb-0">Etes-vous sûr que vous voulez supprimer: </p>
            </div>
            <div class="modal-footer">
                <form id="delete-form">
                    {% csrf_token %}
                    <button type="button" class="btn  btn-secondary" data-dismiss="modal">Fermer</button>
                    <button type="submit" class="btn  btn-danger">Supprimer</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Delete Selected start -->
<div id="deleteSelectedModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel4"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel4">Supprimer les catégories sélectionnée</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <p class="mb-0"></p>
                <p id="delMsgName"></p>
            </div>
            <div class="modal-footer">
                <form id="delete-selected-form">
                    {% csrf_token %}
                    <button type="button" class="btn  btn-secondary" data-dismiss="modal">Fermer</button>
                    <button type="submit" class="btn  btn-danger" id="submitDelSel">Ok</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row justify-content-center">
    <!-- [ sample-page ] start -->
    <div class="col-sm-9">
        <div class="card">
            <div class="card-header">
                <h5>Categories</h5>
                <div class="d-flex flex-wrap justify-content-around mt-3">
                    <div>
                        <button type="button" class="btn btn-success mr-3" data-toggle="modal" data-target="#addModal">
                            Ajouter une categorie
                        </button>
                        <button type="button" class="btn btn-danger" id="delete-selected-btn" data-toggle="modal"
                            data-target="#deleteSelectedModal">Supprimer la sélection
                        </button>
                    </div>
                </div>
                <div class="card-header-right">
                    <div class="btn-group card-option">
                        <button type="button" class="btn dropdown-toggle btn-icon" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <i class="feather icon-more-horizontal"></i>
                        </button>
                        <ul class="list-unstyled card-option dropdown-menu dropdown-menu-right">
                            <li class="dropdown-item full-card"><a href="#!"><span><i class="feather icon-maximize"></i>
                                        maximiser</span><span style="display:none"><i class="feather icon-minimize"></i>
                                        restaurer</span></a></li>
                            <li class="dropdown-item minimize-card"><a href="#!"><span><i
                                            class="feather icon-minus"></i> s'effondrer</span><span
                                        style="display:none"><i class="feather icon-plus"></i> agrandir</span></a>
                            </li>
                            <li class="dropdown-item reload-card"><a href="#!"><i class="feather icon-refresh-cw"></i>
                                    recharger</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="card-body table-border-style">
                <div id="alert-box"></div>
                <div class="dt-responsive table-responsive">
                    <table id="row-select" class="table table-striped table-bordered nowrap ">
                        <thead>
                            <tr>
                                <th>N°</th>
                                <th>Categorie</th>
                                <th>Produit/Cat</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody id="rows-box"></tbody>
                    </table>
                    <div id="spinner-box" class="text-center">
                        <div class="spinner-border mb-3" role="status"></div>
                    </div>
                    <div class="text-center mb-3 mt-3" id="end-box">
                        <button class="btn btn-primary" id="load-btn">Charger plus</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ sample-page ] end -->
    </div>
    <!-- [ sample-page ] end -->
</div>
<!-- [ List Categories Content ] start -->
{% endblock content %}

ims_soft/products/templates/products/fr/list_products_fr.html
{% load static %}

{% block content %}
<!-- [ List Products Content ] start -->

<!-- Create Product Modal -->
<div id="addModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel">Créer un produit</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div id="alertModal-box"></div>
                <form id="create-form" autocomplete="off">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="">
                        <button type="button" class="btn  btn-secondary" data-dismiss="modal">Fermer</button>
                        <button type="submit" id="add-btn" class="btn  btn-primary">Sauvgarder</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Update  Modal -->
<div id="updateModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel2">Mettre à jour le produit</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <form id="update-form" autocomplete="off">
                    {% csrf_token %}
                    {% crispy form %}
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Delete  start -->
<div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel3"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel3">Supprimer le produit</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <p class="mb-0">Etes-vous sûr que vous voulez supprimer: </p>
                <p id="delMsgName"></p>
            </div>
            <div class="modal-footer">
                <form id="delete-form">
                    {% csrf_token %}
                    <button type="button" class="btn  btn-secondary" data-dismiss="modal">Fermer</button>
                    <button type="submit" class="btn  btn-danger">Supprimer</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Delete Selected start -->
<div id="deleteSelectedModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel4"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel4">Supprimer les produits sélectionnée</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <p id="delSelMsg" class="mb-0"></p>
            </div>
            <div class="modal-footer">
                <form id="delete-selected-form">
                    {% csrf_token %}
                    <button type="button" class="btn  btn-secondary" data-dismiss="modal">Fermer</button>
                    <button type="submit" class="btn  btn-danger" id="submitDelSel">Ok</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <!-- [ sample-page ] start -->
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                <h5>Produits</h5>
                <div class="d-flex flex-wrap justify-content-around mt-3">
                    <div>
                        <button type="button" class="btn btn-success mr-3" data-toggle="modal" data-target="#addModal">
                            Ajouter un produit
                        </button>
                        <button type="button" class="btn btn-danger" id="delete-selected-btn" data-toggle="modal"
                            data-target="#deleteSelectedModal">Supprimer la selection
                        </button>
                    </div>
                    <div>
                        <a href="" class="btn btn-info mr-3">Exporter .Csv</a>
                    </div>
                </div>
                <a href="{% url 'products:export-csv' %}" class="btn btn-info mr-3">Exporter .Csv</a>
                <div class="card-header-right">
                    <div class="btn-group card-option">
                        <button type="button" class="btn dropdown-toggle btn-icon" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <i class="feather icon-more-horizontal"></i>
                        </button>
                        <ul class="list-unstyled card-option dropdown-menu dropdown-menu-right">
                            <li class="dropdown-item full-card"><a href="#!"><span><i class="feather icon-maximize"></i>
                                        maximiser</span><span style="display:none"><i class="feather icon-minimize"></i>
                                        restaurer</span></a></li>
                            <li class="dropdown-item minimize-card"><a href="#!"><span><i
                                            class="feather icon-minus"></i> s'effondrer</span><span
                                        style="display:none"><i class="feather icon-plus"></i> agrandir</span></a>
                            </li>
                            <li class="dropdown-item reload-card"><a href="#!"><i class="feather icon-refresh-cw"></i>
                                    recharger</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="card-body table-border-style">
                <div id="alert-box"></div>
                <div class="dt-responsive table-responsive">
                    <table id="row-select" class="table table-striped table-bordered nowrap ">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nom du produit</th>
                                <th>N° d'Article</th>
                                <th>Categorie</th>
                                <th>Dans Stock</th>
                                <th>Code à barre</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody id="rows-box"></tbody>
                    </table>



                    <div id="spinner-box" class="text-center">
                        <div class="spinner-border mb-3 mt-3" role="status"></div>
                    </div>
                    <div class="text-center mb-3" id="end-box">
                        <button class="btn btn-primary" id="load-btn">Charger plus</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ sample-page ] end -->
    </div>
    <!-- [ sample-page ] end -->
</div>
<!-- [ List Products Content ] start -->
{% endblock content %}